name: SDK CI

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!release-**'
    paths-ignore:
      - '**.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: lint check
        run: gradle check

  unit:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: unit tests
        run: |
          gradle test
          gradle testDebugUnitTest

  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: build project
        run: |
          gradle build
          gradle assembleDebug