name: SDK CI

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - master
      - release*
      - sonatype
    paths-ignore:
      - '**.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: lint check
        run: ./gradlew check

  test:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: unit tests
        run: |
          ./gradlew test
          ./gradlew testDebugUnitTest
  check:
    runs-on: ubuntu-latest
    environment:
      name: Testbed
    steps:
      - uses: actions/checkout@v2
      - name: env check
        run: |
          echo $SONATYPE_USERNAME
          echo $SOME_KEY
        env:
          SONATYPE_USERNAME: ${{secrets.OSSRHUSERNAME}}
          SOME_KEY: ${{secrets.SOME_KEY}}

  build:
    needs: [test, lint]
    runs-on: ubuntu-latest 
    environment:
      name: Testbed
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: build project
        run: |
          ./gradlew assembleDebug
          ./gradlew build -PsonatypeUsername=${{secrets.OSSRHUSERNAME}} -PsonatypePassword=${{secrets.OSSRHPASSWORD}}
