name: SDK Distribute

on:
  push:
    branches:
      - '**'
      - '!master'
    paths-ignore:
      - '**.md'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: feature/MBX-2475
          repository: mindbox-cloud/android-app
          token: ${{ secrets.GITHUBACCESSTOKEN }}
          submodules: true

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Trigger Workflow
        env:
          CI_TOKEN: ${{ secrets.GITHUBACCESSTOKEN }}
          PARENT_REPO: mindbox-cloud/android-app
          PARENT_BRANCH: feature/MBX-2475
          WORKFLOW: distribute.yml
        run: |
          curl -fL --retry 3 -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ env.CI_TOKEN }}" https://api.github.com/repos/${{ env.PARENT_REPO }}/actions/workflows/${{ env.WORKFLOW }}/dispatches -d '{"ref":"${{ env.PARENT_BRANCH }}"}'