name: SDK Distribute

on:
  push:
    branches:
      - '**'
      - '!master'
    paths-ignore:
      - '**.md'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: feature/MBX-2475
          repository: mindbox-cloud/android-app
          token: ${{ secrets.GITHUBACCESSTOKEN }}
          submodules: true

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Trigger Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUBACCESSTOKEN}
          repository: mindbox-cloud/android-app
          event-type: child-repo-push
