name: SDK CI

on:
  push:
    branches:
      - '**'
      - '!master'
    paths-ignore:
      - '**.md'

jobs:
  deploy:
    uses: mindbox-moscow/android-app/.github/workflows/distribute.yml@master
    with:
      commit: $GITHUB_HASH