name: SDK Distribute

on:
  push:
    branches:
      - '**'
      - '!master'
    paths-ignore:
      - '**.md'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: 61033697
          repo: mindbox-cloud/android-app
          ref: feature/MBX-2475
          token: ${{ secrets.GITHUBACCESSTOKEN }}

