name: SDK publish

on:
  push:
    branch:
      - 'master'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: lint check
        run: ./gradlew check

  unit:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: unit tests
        run: |
          ./gradlew test 
          ./gradlew testDebugUnitTest

  build:
    needs: [unit, lint]
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: build project
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: current
          arguments: build

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Prepare to publish
        run: |
          echo '${{secrets.GPGKEYCONTENTS}}' | base64 -d > /tmp/publish_key.gpg
          gpg --quiet --batch --yes --decrypt --passphrase="${{secrets.SECRETPASSPHRASE}}" \
          --output /tmp/secret.gpg /tmp/publish_key.gpg
          echo -e "\nsigning.password=$signingpassword" >> gradle.properties
          echo -e "\nsigning.keyId=$signingkeyId" >> gradle.properties
          echo -e "\nsigning.secretKeyRingFile=/tmp/secret.gpg" >> gradle.properties
        env:
          signingpassword: ${{secrets.signingpassword}}
          signingkeyId: ${{secrets.signingkeyId}}
          SECRETPASSPHRASE: ${{secrets.SECRETPASSPHRASE}}
          GPGKEYCONTENTS: ${{secrets.GPGKEYCONTENTS}}
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Publish with Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: current
          arguments: test publish -PsonatypeUsername=${{secrets.OSSRHUSERNAME}} -PsonatypePassword=${{secrets.OSSRHPASSWORD}}